/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class simkit_smd_Sensor */

#ifndef _Included_simkit_smd_Sensor
#define _Included_simkit_smd_Sensor
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
